#!/usr/bin/with-contenv bash

export RTORRENT_PORT=${RTORRENT_PORT:-"49184-49184"}
export RTORRENT_SCGI_PORT=${RTORRENT_SCGI_PORT:-"5000"}
export RTORRENT_SCGI_HOST=${RTORRENT_SCGI_HOST:-"localhost"}
export RTORRENT_SOCK_PATH=${RTORRENT_SOCK_PATH:-"/config/.sessions/rtorrent.sock"}
export RTORRENT_SOCK=${ROTRRENT_SOCK:-"true"}

_term() {
  echo "Caught SIGTERM signal!"
  killall -TERM rtorrent 2>/dev/null
}

trap _term SIGTERM

cd /app/flood
su-exec abc:abc /usr/bin/npm start &

wait
