#!/usr/bin/with-contenv bash

_term() {
  echo "Caught SIGTERM signal!"
  killall -TERM rtorrent 2>/dev/null
}

trap _term SIGTERM


exec s6-setuidgid abc /usr/bin/rtorrent \
  -n -o import=/config/rtorrent.rc &

wait
