#!/usr/bin/with-contenv bash

RTORRENT_SOCK_PATH=${RTORRENT_SOCK_PATH:-"/config/.sessions/rtorrent.sock"}
RTORRENT_SOCK=${RTORRENT_SOCK:-"true"}
WEBSERVER_PORT=${WEBSERVER_PORT:-80}

if [ $RTORRENT_SOCK == "true" ]; then
  sed -e "s#server unix.*\|server localhost.*#server unix:${RTORRENT_SOCK_PATH};#" -i /config/nginx/site-confs/default
else
  sed -e "s#server unix\|server localhost.*#server localhost:5000;#" -i /config/nginx/site-confs/default
fi
sed -e "s#listen\ .*#listen ${WEBSERVER_PORT} default_server;#" -i /config/nginx/site-confs/default
