#!/usr/bin/with-contenv bash

export FLOOD_SECRET=${FLOOD_SECRET:-"secret"}
RTORRENT_SOCK_PATH=${RTORRENT_SOCK_PATH:-"/config/.sessions/rtorrent.sock"}
RTORRENT_SOCK=${RTORRENT_SOCK:-"true"}

[[ ! -e /config/flood/config.js ]] && \
    mv /app/flood/config.js /config/flood/config.js

ln -fs /config/flood/config.js /app/flood/config.js
sed -e "s#dbPath: .*#dbPath: '/config/flood',#" -i /config/flood/config.js

chown -R abc:abc /data
