#!/usr/bin/with-contenv bash

RTORRENT_PORT=${RTORRENT_PORT:-"49184-49184"}
RTORRENT_SOCK_PATH=${RTORRENT_SOCK_PATH:-"/config/.sessions/rtorrent.sock"}
RTORRENT_SOCK=${RTORRENT_SOCK:-"true"}

if [ $RTORRENT_SOCK == "true" ]; then
  sed -e "s#.*open_local.*\|.*.open_port.*#network.scgi.open_local = ${RTORRENT_SOCK_PATH}#" -i /config/rtorrent.rc
else
  sed -e "s#.*open_local.*\|.*.open_port.*#network.scgi.open_port = localhost:5000#" -i /config/rtorrent.rc
fi

sed -e "s#network.port_range.set.*#network.port_range.set = ${RTORRENT_PORT}#" -i /config/rtorrent.rc

rm -rf /config/.sessions/rtorrent.*
